#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
#ifndef ADBRIXRMKIT_SWIFT_H
#define ADBRIXRMKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdBrixRmKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC11AdBrixRmKit18AbxRemotePushModel")
@interface AbxRemotePushModel : NSObject
- (nullable instancetype)initWithCampaignId:(NSString * _Nonnull)campaignId campaignRevisionNo:(NSInteger)campaignRevisionNo stepId:(NSString * _Nonnull)stepId cycleTime:(NSString * _Nonnull)cycleTime error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class KakaoButton;

SWIFT_CLASS("_TtC11AdBrixRmKit13ActionContent")
@interface ActionContent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable notificationId;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable subtitle;
@property (nonatomic, readonly, copy) NSString * _Nullable body;
@property (nonatomic, readonly, copy) NSString * _Nullable bigTextTitle;
@property (nonatomic, readonly, copy) NSString * _Nullable bigTextBody;
@property (nonatomic, readonly, copy) NSString * _Nullable summaryText;
@property (nonatomic, readonly, copy) NSString * _Nullable imgUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable largeIconUrl;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable deeplinkJson;
@property (nonatomic, readonly, copy) NSString * _Nullable deeplinkUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable imageClickLink;
@property (nonatomic, readonly, copy) NSArray<KakaoButton *> * _Nullable kakaoButtons;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AdBrixRmKit13ActionHistory")
@interface ActionHistory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull historyId;
@property (nonatomic, readonly, copy) NSString * _Nonnull actionType;
@property (nonatomic, readonly) int64_t timeStamp;
@property (nonatomic, readonly, strong) ActionContent * _Nonnull content;
@property (nonatomic, readonly) BOOL isRead;
@property (nonatomic, readonly, copy) NSString * _Nonnull group;
@property (nonatomic, readonly) BOOL isServerSynced;
- (NSString * _Nonnull)toJsonString SWIFT_WARN_UNUSED_RESULT;
+ (ActionHistory * _Nullable)fromDictionaryWithHistoryJsonDic:(NSDictionary<NSString *, id> * _Nonnull)historyJsonDic isServerSynced:(BOOL)isServerSynced SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ActionHistoryIdType, open) {
  ActionHistoryIdTypeUSER_ID = 0,
  ActionHistoryIdTypeADID = 1,
};


SWIFT_CLASS("_TtC11AdBrixRmKit19ActionHistoryResult")
@interface ActionHistoryResult : NSObject
@property (nonatomic, readonly) BOOL isSucceeded;
- (NSArray<ActionHistory *> * _Nullable)getData SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nullable)getError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UNNotificationRequest;
@class UNNotificationContent;

SWIFT_CLASS("_TtC11AdBrixRmKit33AdBrixMultiPushProviderController")
@interface AdBrixMultiPushProviderController : NSObject
+ (AdBrixMultiPushProviderController * _Nonnull)getInstanceObjc SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)didReceiveAbxPush:(UNNotificationRequest * _Nonnull)request withContentHandler:(void (^ _Nonnull)(UNNotificationContent * _Nonnull))contentHandler;
- (void)abxPushServiceExtensionTimeWillExpire;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit17AdBrixPushService")
@interface AdBrixPushService : UNNotificationServiceExtension
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)didReceiveNotificationRequest:(UNNotificationRequest * _Nonnull)request withContentHandler:(void (^ _Nonnull)(UNNotificationContent * _Nonnull))contentHandler;
- (void)serviceExtensionTimeWillExpire;
@end

enum AdBrixEventUploadCountInterval : NSInteger;
enum AdBrixEventUploadTimeInterval : NSInteger;
@class NSURL;
enum AdBrixGenderType : NSInteger;
@class AdBrixRmAttrModel;
@class SetCiProfileResult;
enum AdBrixRmSignUpChannel : NSInteger;
enum AdBrixRmInviteChannel : NSInteger;
@class AdBrixRmCommerceProductModel;
enum AdbrixRmPaymentMethod : NSInteger;
@class AdBrixRmCommerceProductCategoryModel;
enum AdBrixRmCurrencyType : NSInteger;
@class GetSubscriptionResult;
@class SubscriptionStatus;
@class SetSubscriptionResult;
enum AdBrixRmSharingChannel : NSInteger;
enum Completion : NSInteger;
@class NSData;
@protocol AdBrixRmPushLocalDelegate;
@protocol AdBrixRmPushRemoteDelegate;
@class NSDate;
@class UNNotificationSound;
@class NSNumber;
@class UNUserNotificationCenter;
@class UNNotificationResponse;
@class SelfServeInAppMessage;
@class DfnInAppMessageResult;
@class DfnInAppMessageFetchResult;
@protocol AdBrixRMLogDelegate;
@protocol AdBrixRMInAppMessageClickDelegate;
@protocol DfnInAppMessageAutoFetchDelegate;
@protocol AdBrixRMDeeplinkDelegate;
@protocol AdBrixRMDeferredDeeplinkDelegate;
@class DfnResult;

SWIFT_CLASS("_TtC11AdBrixRmKit8AdBrixRM")
@interface AdBrixRM : NSObject
+ (AdBrixRM * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)stopGettingIDFA;
- (void)startGettingIDFA;
- (void)initAdBrixWithAppKey:(NSString * _Nonnull)appKey secretKey:(NSString * _Nonnull)secretKey SWIFT_METHOD_FAMILY(none);
- (void)setEventUploadCountInterval:(enum AdBrixEventUploadCountInterval)countInterval;
- (enum AdBrixEventUploadCountInterval)convertCountInterval:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (void)setEventUploadTimeInterval:(enum AdBrixEventUploadTimeInterval)timeInterval;
- (enum AdBrixEventUploadTimeInterval)convertTimeInterval:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (void)gdprForgetMe;
- (BOOL)isGdprForgetMe SWIFT_WARN_UNUSED_RESULT;
- (void)deepLinkOpenWithUrlStr:(NSString * _Nonnull)urlStr;
- (void)deepLinkOpenWithUrl:(NSURL * _Nonnull)url;
- (void)loginWithUserId:(NSString * _Nonnull)userId;
- (void)logout;
- (void)getUserIdWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (void)setAgeWithInt:(NSInteger)int_;
- (void)setGenderWithAdBrixGenderType:(enum AdBrixGenderType)adBrixGenderType;
- (enum AdBrixGenderType)convertGender:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (void)setUserPropertiesWithAttrWithAttrModel:(AdBrixRmAttrModel * _Nonnull)attrModel;
- (void)clearUserProperties SWIFT_DEPRECATED;
- (void)setKakaoIdWithKakaoId:(NSString * _Nonnull)kakaoId SWIFT_DEPRECATED_MSG("use setKakaoId(kakaoId:completion:) instead");
/// This function is used to set a phone number for a user. ex) 821012345678
/// \param number The phone number to set for the user. This must conform to the E.164 standard but without “+”. An example of an E.164 formatted number without “+” could be “821012345678”. For more information on E.164, refer to <a href="https://en.wikipedia.org/wiki/E.164">E.164 - Wikipedia</a>
///
/// \param completion A closure that is called when the operation is complete. It passes a <code>SetCiProfileResult</code> object that describes the result of the operation.
/// <ul>
///   <li>
///     <code>isSuccess</code>: A Boolean value indicating whether the operation was successful.
///   </li>
///   <li>
///     <code>resultCode</code>: A result code from server
///   </li>
///   <li>
///     <code>resultMessage</code>: A result message from server
///   </li>
/// </ul>
///
- (void)setPhoneNumberWithNumber:(NSString * _Nonnull)number completion:(void (^ _Nonnull)(SetCiProfileResult * _Nonnull))completion;
/// This function is used to set a Kakao ID for a user. KakaoId must be a 10-digit ID from Kakao Sync API
/// \param kakaoId The Kakao ID to set for the user. This must be a 10-digit ID obtained from the Kakao Sync API.
///
/// \param completion A closure that is called when the operation is complete. It passes a <code>SetCiProfileResult</code> object that describes the result of the operation.
/// <ul>
///   <li>
///     <code>isSuccess</code>: A Boolean value indicating whether the operation was successful.
///   </li>
///   <li>
///     <code>resultCode</code>: A result code from server
///   </li>
///   <li>
///     <code>resultMessage</code>: A result message from server
///   </li>
/// </ul>
///
- (void)setKakaoIdWithKakaoId:(NSString * _Nonnull)kakaoId completion:(void (^ _Nonnull)(SetCiProfileResult * _Nonnull))completion;
- (void)setUserCiWithAttrWithAttrModel:(AdBrixRmAttrModel * _Nonnull)attrModel SWIFT_DEPRECATED;
- (void)setLocationWithLatitude:(double)latitude longitude:(double)longitude SWIFT_DEPRECATED;
- (void)eventWithEventName:(NSString * _Nonnull)eventName;
- (void)eventWithAttrWithEventName:(NSString * _Nonnull)eventName value:(AdBrixRmAttrModel * _Nonnull)value;
- (void)commonSignUpWithChannel:(enum AdBrixRmSignUpChannel)channel;
- (void)commonSignUpWithAttrWithChannel:(enum AdBrixRmSignUpChannel)channel commonAttr:(AdBrixRmAttrModel * _Nullable)commonAttr;
- (NSString * _Nonnull)getSignUpChannelByAdBrixRmSignUpChannel:(enum AdBrixRmSignUpChannel)channel SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSignUpChannel:(NSInteger)channel SWIFT_WARN_UNUSED_RESULT;
- (enum AdBrixRmSignUpChannel)convertSignUpChannel:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (void)commonAppUpdateWithPrev_ver:(NSString * _Nonnull)prev_ver curr_ver:(NSString * _Nonnull)curr_ver;
- (void)commonAppUpdateWithAttrWithPrev_ver:(NSString * _Nonnull)prev_ver curr_ver:(NSString * _Nonnull)curr_ver commonAttr:(AdBrixRmAttrModel * _Nullable)commonAttr;
- (void)commonInviteWithChannel:(enum AdBrixRmInviteChannel)channel;
- (void)commonInviteWithAttrWithChannel:(enum AdBrixRmInviteChannel)channel commonAttr:(AdBrixRmAttrModel * _Nullable)commonAttr;
- (NSString * _Nonnull)getInviteChannelByAdBrixRmSignUpChannel:(enum AdBrixRmInviteChannel)channel SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getInviteChannel:(NSInteger)channel SWIFT_WARN_UNUSED_RESULT;
- (enum AdBrixRmInviteChannel)convertInviteChannel:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (void)commonUseCredit;
- (void)commonUseCreditWithAttrWithCommonAttr:(AdBrixRmAttrModel * _Nullable)commonAttr;
- (void)commonPurchaseWithOrderId:(NSString * _Nonnull)orderId productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo orderSales:(double)orderSales discount:(double)discount deliveryCharge:(double)deliveryCharge paymentMethod:(enum AdbrixRmPaymentMethod)paymentMethod;
- (void)commonPurchaseWithAttrWithOrderId:(NSString * _Nonnull)orderId productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo orderSales:(double)orderSales discount:(double)discount deliveryCharge:(double)deliveryCharge paymentMethod:(enum AdbrixRmPaymentMethod)paymentMethod orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (NSString * _Nonnull)getPaymentMethodByAdbrixRmPaymentMethod:(enum AdbrixRmPaymentMethod)method SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getPaymentMethod:(NSInteger)method SWIFT_WARN_UNUSED_RESULT;
- (enum AdbrixRmPaymentMethod)convertPayment:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (AdBrixRmCommerceProductModel * _Nonnull)createCommerceProductDataWithAttrWithProductId:(NSString * _Nonnull)productId productName:(NSString * _Nonnull)productName price:(double)price quantity:(NSInteger)quantity discount:(double)discount currencyString:(NSString * _Nullable)currencyString category:(AdBrixRmCommerceProductCategoryModel * _Nullable)category productAttrsMap:(AdBrixRmAttrModel * _Nullable)productAttrsMap SWIFT_WARN_UNUSED_RESULT;
- (AdBrixRmAttrModel * _Nonnull)createAttrModelWithDictionary:(NSDictionary<NSString *, NSString *> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (AdBrixRmCommerceProductCategoryModel * _Nonnull)createCommerceProductCategoryDataWithCategory:(NSString * _Nonnull)category category2:(NSString * _Nonnull)category2 category3:(NSString * _Nonnull)category3 category4:(NSString * _Nonnull)category4 category5:(NSString * _Nonnull)category5 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCurrencyStringByAdBrixCurrencyType:(enum AdBrixRmCurrencyType)currency SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCurrencyString:(NSInteger)currency SWIFT_WARN_UNUSED_RESULT;
- (void)commerceViewHome;
- (void)commerceViewHomeWithAttrWithOrderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceCategoryViewWithCategory:(AdBrixRmCommerceProductCategoryModel * _Nonnull)category productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo;
/// Retrieves the subscription status and returns the result in the form of a <code>GetSubscriptionResult</code> object.
/// <ul>
///   <li>
///     GetSubscriptionResult:
///     <ul>
///       <li>
///         isSuccess: Bool
///       </li>
///       <li>
///         value: SubscriptionStatus?
///       </li>
///       <li>
///         resultCode: Int?
///       </li>
///       <li>
///         resultMessage: String?
///       </li>
///     </ul>
///   </li>
/// </ul>
/// <hr/>
/// <ul>
///   <li>
///     Example:
///   </li>
/// </ul>
/// \code
/// getSubscriptionStatus { result in
///    if result.isSuccess {
///        if let status = result.value {
///            //handle SubscriptionStatus
///            print(value.marketingNotificationFlag.isSubscribed)
///        }
///    } else {
///        if let error = result.error {
///            //handle error
///            print(error.resultCode)
///            print(error.resultMessage)
///        }
///    }
/// }
///
/// \endcode<ul>
///   <li>
///     Notice:
///     userId must be set before calling this function.
///   </li>
/// </ul>
- (void)getSubscriptionStatusWithCompletion:(void (^ _Nonnull)(GetSubscriptionResult * _Nonnull))completion;
/// Set subscription status of current user and returns the result in the form of a <code>SetSubscriptionResult</code> object.
/// <hr/>
/// Example:
/// \code
/// let status = SubscriptionStatus.Builder()
///    .setInformativeNotificationFlag(to: .SUBSCRIBED)
///    .setMarketingNotificationFlag(to: .UNSUBSCRIBED)
///    .setMarketingNotificationFlagForKakaoChannel(to: .UNSUBSCRIBED)
///    .setMarketingNotificationFlagForSmsChannel(to: .SUBSCRIBED)
///    .setMarketingNotificationFlagForPushChannel(to: .UNSUBSCRIBED)
///    .setMarketingNotificationAtNightFlag(to: .UNSUBSCRIBED)
///    .setMarketingNotificationAtNightFlagForSmsChannel(to: .UNSUBSCRIBED)
///    .setMarketingNotificationAtNightFlagForKakaoChannel(to: .UNSUBSCRIBED)
///    .setMarketingNotificationAtNightFlagForPushChannel(to: .UNSUBSCRIBED)
///    .build()
///
/// AdBrixRm.setSubscriptionStatus(status: status) { result in
///    if result.isSuccess {
///        print("success")
///    } else {
///        print(result.error?.localizedDescription)
///    }
/// }
///
/// \endcodeor
/// \code
/// SubscriptionStatus.Builder()
///     .setInformativeNotificationFlag(to: .SUBSCRIBED)
///     .setMarketingNotificationFlag(to: .SUBSCRIBED)
///     .setMarketingNotificationFlagForPushChannel(to: .SUBSCRIBED)
///     .build()
///     .send { result in
///     if result.isSuccess {
///        print("success")
///     } else {
///        print(result.resultMessage)
///        print(result.resultCode)
///     }
///
///
/// \endcode\param status SubscriptionStatus made by SubscriptionStatus.Builder().build()
///
/// \param completion SetSubscriptionResult - isSuccess: Bool, resultCode: Int?, resultMessage: String?
///
- (void)setSubscriptionStatusWithStatus:(SubscriptionStatus * _Nonnull)status completion:(void (^ _Nonnull)(SetSubscriptionResult * _Nonnull))completion;
- (void)commerceCategoryViewWithAttrWithCategory:(AdBrixRmCommerceProductCategoryModel * _Nonnull)category productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceProductViewWithProductInfo:(AdBrixRmCommerceProductModel * _Nonnull)productInfo;
- (void)commerceProductViewWithAttrWithProductInfo:(AdBrixRmCommerceProductModel * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceAddToCartWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo;
- (void)commerceAddToCartWithAttrWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceAddToWishList:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo;
- (void)commerceAddToWishList:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo withAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceAddToWishListWithProductInfo:(AdBrixRmCommerceProductModel * _Nonnull)productInfo;
- (void)commerceAddToWishListWithAttrWithProductInfo:(AdBrixRmCommerceProductModel * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceReviewOrderWithOrderId:(NSString * _Nonnull)orderId productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo discount:(double)discount deliveryCharge:(double)deliveryCharge;
- (void)commerceReviewOrderWithAttrWithOrderId:(NSString * _Nonnull)orderId productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo discount:(double)discount deliveryCharge:(double)deliveryCharge orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceRefundWithOrderId:(NSString * _Nonnull)orderId productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo penaltyCharge:(double)penaltyCharge;
- (void)commerceRefundWithAttrWithOrderId:(NSString * _Nonnull)orderId productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo penaltyCharge:(double)penaltyCharge orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceSearchWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo keyword:(NSString * _Nonnull)keyword;
- (void)commerceSearchWithAttrWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo keyword:(NSString * _Nonnull)keyword orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceShare:(enum AdBrixRmSharingChannel)channel productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo;
- (void)commerceShareWithAttr:(enum AdBrixRmSharingChannel)channel productInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceShareWithChannel:(enum AdBrixRmSharingChannel)channel productInfo:(AdBrixRmCommerceProductModel * _Nonnull)productInfo;
- (void)commerceShareWithAttrWithChannel:(enum AdBrixRmSharingChannel)channel productInfo:(AdBrixRmCommerceProductModel * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (NSString * _Nonnull)getSharingChannelByAdBrixRmSharingChannel:(enum AdBrixRmSharingChannel)channel SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSharingChannel:(NSInteger)channel SWIFT_WARN_UNUSED_RESULT;
- (enum AdBrixRmSharingChannel)convertChannel:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (void)commerceListViewWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo;
- (void)commerceListViewWithAttrWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commerceCartViewWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo;
- (void)commerceCartViewWithAttrWithProductInfo:(NSArray<AdBrixRmCommerceProductModel *> * _Nonnull)productInfo orderAttr:(AdBrixRmAttrModel * _Nullable)orderAttr;
- (void)commercePaymentInfoAdded;
- (void)commercePaymentInfoAddedWithAttrWithPaymentInfoAttr:(AdBrixRmAttrModel * _Nullable)paymentInfoAttr;
- (void)gameTutorialCompletedWithIsSkip:(BOOL)isSkip;
- (void)gameTutorialCompletedWithAttrWithIsSkip:(BOOL)isSkip gameInfoAttr:(AdBrixRmAttrModel * _Nullable)gameInfoAttr;
- (void)gameCharacterCreated;
- (void)gameCharacterCreatedWithAttrWithGameInfoAttr:(AdBrixRmAttrModel * _Nullable)gameInfoAttr;
- (void)gameStageClearedWithStageName:(NSString * _Nonnull)stageName;
- (void)gameStageClearedWithAttrWithStageName:(NSString * _Nonnull)stageName gameInfoAttr:(AdBrixRmAttrModel * _Nullable)gameInfoAttr;
- (void)gameLevelAchievedWithLevel:(NSInteger)level;
- (void)gameLevelAchievedWithAttrWithLevel:(NSInteger)level gameInfoAttr:(AdBrixRmAttrModel * _Nullable)gameInfoAttr;
- (void)deleteUserDataAndStopSDK:(NSString * _Nonnull)userId :(void (^ _Nonnull)(enum Completion))completion SWIFT_DEPRECATED;
- (void)restartSDK:(NSString * _Nonnull)userId :(void (^ _Nonnull)(enum Completion))completion SWIFT_DEPRECATED;
- (void)setRegistrationIdWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)setPushEnableToPushEnable:(BOOL)toPushEnable;
- (void)fetchActionHistoryByUserIdWithToken:(NSString * _Nullable)token actionType:(NSArray<NSString *> * _Nonnull)actionType completion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)fetchActionHistoryByAdidWithToken:(NSString * _Nullable)token actionType:(NSArray<NSString *> * _Nonnull)actionType completion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)insertPushDataWithPushJsonDic:(NSDictionary<NSString *, id> * _Nonnull)pushJsonDic;
- (void)getActionHistoryWithSkip:(NSInteger)skip limit:(NSInteger)limit actionType:(NSArray<NSString *> * _Nonnull)actionType completion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)getAllActionHistoryWithActionType:(NSArray<NSString *> * _Nonnull)actionType completion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)deleteAllActionHistoryByUserIdWithToken:(NSString * _Nullable)token completion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)deleteAllActionHistoryByAdidWithToken:(NSString * _Nullable)token completion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)deleteActionHistoryWithToken:(NSString * _Nullable)token historyId:(NSString * _Nonnull)historyId timeStamp:(int64_t)timeStamp completion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)clearSyncedActionHistoryInLocalDBWithCompletion:(void (^ _Nonnull)(ActionHistoryResult * _Nonnull))completion;
- (void)clearAllActionHistoryInLocalDB;
- (void)setAdBrixRmPushLocalDelegateWithDelegate:(id <AdBrixRmPushLocalDelegate> _Nonnull)delegate;
- (void)setAdBrixRmPushRemoteDelegateWithDelegate:(id <AdBrixRmPushRemoteDelegate> _Nonnull)delegate;
- (void)registerLocalPushNotificationWithDate:(NSDate * _Nonnull)date title:(NSString * _Nonnull)title subtitle:(NSString * _Nullable)subtitle body:(NSString * _Nonnull)body sound:(UNNotificationSound * _Nullable)sound categoryId:(NSString * _Nullable)categoryId threadId:(NSString * _Nullable)threadId badgeNumber:(NSNumber * _Nullable)badgeNumber image:(NSURL * _Nullable)image attrDic:(NSDictionary<NSString *, id> * _Nullable)attrDic completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable, NSString * _Nonnull))completionHandler;
- (void)registerLocalPushNotificationWithId:(NSString * _Nonnull)id date:(NSDate * _Nonnull)date title:(NSString * _Nonnull)title subtitle:(NSString * _Nullable)subtitle body:(NSString * _Nonnull)body sound:(UNNotificationSound * _Nullable)sound categoryId:(NSString * _Nullable)categoryId threadId:(NSString * _Nullable)threadId badgeNumber:(NSNumber * _Nullable)badgeNumber image:(NSURL * _Nullable)image attrDic:(NSDictionary<NSString *, id> * _Nullable)attrDic completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable, NSString * _Nonnull))completionHandler;
- (void)getRegisteredLocalPushNotificationWithCompleteHandler:(void (^ _Nonnull)(NSArray<NSString *> * _Nonnull))completeHandler;
- (void)cancelLocalPushNotificationWithIds:(NSArray<NSString *> * _Nonnull)ids;
- (void)cancelLocalPushNotificationAll;
- (void)userNotificationCenterWithCenter:(UNUserNotificationCenter * _Nonnull)center response:(UNNotificationResponse * _Nonnull)response;
- (AbxRemotePushModel * _Nullable)parsePushData:(NSDictionary * _Nonnull)pushDict error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)openPush:(AbxRemotePushModel * _Nonnull)abxRemotePushModel;
- (void)didReceiveAbxPush:(UNNotificationRequest * _Nonnull)request withContentHandler:(void (^ _Nonnull)(UNNotificationContent * _Nonnull))contentHandler;
- (void)abxPushServiceExtensionTimeWillExpire;
- (void)getSelfServeInAppMessagesWithCompletion:(void (^ _Nonnull)(NSArray<SelfServeInAppMessage *> * _Nonnull))completion;
- (void)getAllInAppMessageWithCompletion:(void (^ _Nonnull)(DfnInAppMessageResult * _Nonnull))completion SWIFT_DEPRECATED;
- (void)openInAppMessageWithCampaignId:(NSString * _Nonnull)campaignId completion:(void (^ _Nonnull)(enum Completion))completion;
- (void)fetchInAppMessageWithCompletion:(void (^ _Nonnull)(DfnInAppMessageFetchResult * _Nonnull))completion;
- (void)setInAppMessageTokenWithToken:(NSString * _Nonnull)token;
- (void)pauseInAppMessage;
- (void)resumeInAppMessage;
- (void)setLogDelegateWithDelegate:(id <AdBrixRMLogDelegate> _Nonnull)delegate;
- (void)setInAppMessageClickDelegateWithDelegate:(id <AdBrixRMInAppMessageClickDelegate> _Nonnull)delegate;
- (void)setInAppMessageAutoFetchDelegateWithDelegate:(id <DfnInAppMessageAutoFetchDelegate> _Nonnull)delegate;
- (void)printSdkState;
- (void)setDeeplinkDelegateWithDelegate:(id <AdBrixRMDeeplinkDelegate> _Nonnull)delegate;
- (void)setDeferredDeeplinkDelegateWithDelegate:(id <AdBrixRMDeferredDeeplinkDelegate> _Nonnull)delegate;
- (void)setDeviceId:(NSString * _Nonnull)device_id;
- (void)flushAllEventsWithCompletion:(void (^ _Nullable)(DfnResult * _Nonnull))completion;
- (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
- (void)didBecomeActive;
- (void)willResignActive;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, AdBrixEventUploadCountInterval, open) {
  AdBrixEventUploadCountIntervalMIN = 10,
  AdBrixEventUploadCountIntervalNORMAL = 30,
  AdBrixEventUploadCountIntervalMAX = 60,
};

typedef SWIFT_ENUM(NSInteger, AdBrixEventUploadTimeInterval, open) {
  AdBrixEventUploadTimeIntervalMIN = 30,
  AdBrixEventUploadTimeIntervalNORMAL = 60,
  AdBrixEventUploadTimeIntervalMAX = 120,
};

typedef SWIFT_ENUM(NSInteger, AdBrixLogLevel, open) {
  AdBrixLogLevelNONE = 0,
  AdBrixLogLevelTRACE = 1,
  AdBrixLogLevelDEBUG = 2,
  AdBrixLogLevelINFO = 3,
  AdBrixLogLevelWARNING = 4,
  AdBrixLogLevelERROR = 5,
};

typedef SWIFT_ENUM(NSInteger, AdBrixGenderType, open) {
  AdBrixGenderTypeMale = 2,
  AdBrixGenderTypeFemale = 1,
  AdBrixGenderTypeUnknown = 0,
};

typedef SWIFT_ENUM(NSInteger, AdBrixRmSignUpChannel, open) {
  AdBrixRmSignUpChannelAdBrixRmSignUpKakaoChannel = 1,
  AdBrixRmSignUpChannelAdBrixRmSignUpNaverChannel = 2,
  AdBrixRmSignUpChannelAdBrixRmSignUpLineChannel = 3,
  AdBrixRmSignUpChannelAdBrixRmSignUpGoogleChannel = 4,
  AdBrixRmSignUpChannelAdBrixRmSignUpFacebookChannel = 5,
  AdBrixRmSignUpChannelAdBrixRmSignUpTwitterChannel = 6,
  AdBrixRmSignUpChannelAdBrixRmSignUpWhatsAppChannel = 7,
  AdBrixRmSignUpChannelAdBrixRmSignUpQQChannel = 8,
  AdBrixRmSignUpChannelAdBrixRmSignUpWeChatChannel = 9,
  AdBrixRmSignUpChannelAdBrixRmSignUpUserIdChannel = 10,
  AdBrixRmSignUpChannelAdBrixRmSignUpETCChannel = 11,
  AdBrixRmSignUpChannelAdBrixRmSignUpSkTidChannel = 12,
  AdBrixRmSignUpChannelAdBrixRmSignUpAppleIdChannel = 13,
};

typedef SWIFT_ENUM(NSInteger, AdBrixRmInviteChannel, open) {
  AdBrixRmInviteChannelAdBrixRmInviteKakaoChannel = 1,
  AdBrixRmInviteChannelAdBrixRmInviteNaverChannel = 2,
  AdBrixRmInviteChannelAdBrixRmInviteLineChannel = 3,
  AdBrixRmInviteChannelAdBrixRmInviteGoogleChannel = 4,
  AdBrixRmInviteChannelAdBrixRmInviteFacebookChannel = 5,
  AdBrixRmInviteChannelAdBrixRmInviteTwitterChannel = 6,
  AdBrixRmInviteChannelAdBrixRmInviteWhatsAppChannel = 7,
  AdBrixRmInviteChannelAdBrixRmInviteQQChannel = 8,
  AdBrixRmInviteChannelAdBrixRmInviteWeChatChannel = 9,
  AdBrixRmInviteChannelAdBrixRmInviteETCChannel = 10,
};

typedef SWIFT_ENUM(NSInteger, AdBrixRmCurrencyType, open) {
  AdBrixRmCurrencyTypeKRW = 1,
  AdBrixRmCurrencyTypeUSD = 2,
  AdBrixRmCurrencyTypeJPY = 3,
  AdBrixRmCurrencyTypeEUR = 4,
  AdBrixRmCurrencyTypeGBP = 5,
  AdBrixRmCurrencyTypeCNY = 6,
  AdBrixRmCurrencyTypeTWD = 7,
  AdBrixRmCurrencyTypeHKD = 8,
  AdBrixRmCurrencyTypeIDR = 9,
  AdBrixRmCurrencyTypeINR = 10,
  AdBrixRmCurrencyTypeRUB = 11,
  AdBrixRmCurrencyTypeTHB = 12,
  AdBrixRmCurrencyTypeVND = 13,
  AdBrixRmCurrencyTypeMYR = 14,
};

typedef SWIFT_ENUM(NSInteger, AdbrixRmPaymentMethod, open) {
  AdbrixRmPaymentMethodCreditCard = 1,
  AdbrixRmPaymentMethodBankTransfer = 2,
  AdbrixRmPaymentMethodMobilePayment = 3,
  AdbrixRmPaymentMethodETC = 4,
};

typedef SWIFT_ENUM(NSInteger, AdBrixRmSharingChannel, open) {
  AdBrixRmSharingChannelAdBrixRmSharingFacebook = 1,
  AdBrixRmSharingChannelAdBrixRmSharingKakaoTalk = 2,
  AdBrixRmSharingChannelAdBrixRmSharingKakaoStory = 3,
  AdBrixRmSharingChannelAdBrixRmSharingLine = 4,
  AdBrixRmSharingChannelAdBrixRmSharingWhatsApp = 5,
  AdBrixRmSharingChannelAdBrixRmSharingQQ = 6,
  AdBrixRmSharingChannelAdBrixRmSharingWeChat = 7,
  AdBrixRmSharingChannelAdBrixRmSharingSMS = 8,
  AdBrixRmSharingChannelAdBrixRmSharingEmail = 9,
  AdBrixRmSharingChannelAdBrixRmSharingCopyUrl = 10,
  AdBrixRmSharingChannelAdBrixRmSharingETC = 11,
};


SWIFT_PROTOCOL("_TtP11AdBrixRmKit24AdBrixRMDeeplinkDelegate_")
@protocol AdBrixRMDeeplinkDelegate
- (void)didReceiveDeeplinkWithDeeplink:(NSString * _Nonnull)deeplink;
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit32AdBrixRMDeferredDeeplinkDelegate_")
@protocol AdBrixRMDeferredDeeplinkDelegate
- (void)didReceiveDeferredDeeplinkWithDeeplink:(NSString * _Nonnull)deeplink;
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit33AdBrixRMInAppMessageClickDelegate_")
@protocol AdBrixRMInAppMessageClickDelegate
- (void)onReceiveInAppMessageClickWithActionId:(NSString * _Nonnull)actionId actionType:(NSString * _Nonnull)actionType actionArg:(NSString * _Nonnull)actionArg isClosed:(BOOL)isClosed;
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit19AdBrixRMLogDelegate_")
@protocol AdBrixRMLogDelegate
- (void)didPrintLogWithLevel:(enum AdBrixLogLevel)level log:(NSString * _Nonnull)log;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit17AdBrixRmAttrModel")
@interface AdBrixRmAttrModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)getAttrData SWIFT_WARN_UNUSED_RESULT;
- (void)setAttrDataString:(NSString * _Nonnull)key :(NSString * _Nonnull)value;
- (void)setAttrDataDouble:(NSString * _Nonnull)key :(double)value;
- (void)setAttrDataUInt64:(NSString * _Nonnull)key :(uint64_t)value;
- (void)setAttrDataInt64:(NSString * _Nonnull)key :(int64_t)value;
- (void)setAttrDataInt:(NSString * _Nonnull)key :(NSInteger)value;
- (void)setAttrDataBool:(NSString * _Nonnull)key :(BOOL)value;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit36AdBrixRmCommerceProductCategoryModel")
@interface AdBrixRmCommerceProductCategoryModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (AdBrixRmCommerceProductCategoryModel * _Nonnull)setModelWithCategoryArr:(NSArray<NSString *> * _Nonnull)categoryArr SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit28AdBrixRmCommerceProductModel")
@interface AdBrixRmCommerceProductModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (AdBrixRmCommerceProductModel * _Nonnull)setModelWithProductId:(NSString * _Nonnull)productId productName:(NSString * _Nonnull)productName price:(double)price quantity:(NSInteger)quantity discount:(double)discount currencyString:(NSString * _Nullable)currencyString categories:(AdBrixRmCommerceProductCategoryModel * _Nullable)categories productAttrsMap:(AdBrixRmAttrModel * _Nullable)productAttrsMap SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit25AdBrixRmPushLocalDelegate_")
@protocol AdBrixRmPushLocalDelegate
- (void)pushLocalCallbackWithData:(NSDictionary<NSString *, id> * _Nullable)data state:(enum UIApplicationState)state;
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit36AdBrixRmPushNoticePopupCloseDelegate_")
@protocol AdBrixRmPushNoticePopupCloseDelegate
- (void)noticePopupCloseCallbackWithPopupSpaceKey:(NSString * _Nonnull)popupSpaceKey data:(NSDictionary<NSString *, id> * _Nullable)data;
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit40AdBrixRmPushNoticePopupLinkClickDelegate_")
@protocol AdBrixRmPushNoticePopupLinkClickDelegate
- (void)noticePopupLinkClickCallbackWithPopupSpaceKey:(NSString * _Nonnull)popupSpaceKey data:(NSDictionary<NSString *, id> * _Nullable)data;
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit26AdBrixRmPushRemoteDelegate_")
@protocol AdBrixRmPushRemoteDelegate
- (void)pushRemoteCallbackWithData:(NSDictionary<NSString *, id> * _Nullable)data state:(enum UIApplicationState)state;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit8CIResult")
@interface CIResult : NSObject
@property (nonatomic, readonly) BOOL isSuccess;
@property (nonatomic, readonly, copy) NSString * _Nullable resultMessage;
@property (nonatomic, readonly, strong) NSNumber * _Nullable resultCodeObjc;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Completion, open) {
  CompletionSuccess = 0,
  CompletionFail = 1,
};


SWIFT_CLASS("_TtC11AdBrixRmKit13DfnIAMTrigger")
@interface DfnIAMTrigger : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nullable eventName;
@property (nonatomic, readonly) int64_t priority;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AdBrixRmKit15DfnInAppMessage")
@interface DfnInAppMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull campaignId;
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly, copy) NSString * _Nullable position;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull html;
@property (nonatomic, readonly, copy) NSString * _Nonnull bgColor;
@property (nonatomic, readonly, copy) NSString * _Nonnull overlayColor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP11AdBrixRmKit32DfnInAppMessageAutoFetchDelegate_")
@protocol DfnInAppMessageAutoFetchDelegate
- (void)didFetchInAppMessageWithResult:(DfnInAppMessageFetchResult * _Nonnull)result;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit26DfnInAppMessageFetchResult")
@interface DfnInAppMessageFetchResult : NSObject
@property (nonatomic, readonly) BOOL isSucceeded;
- (NSError * _Nullable)getError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AdBrixRmKit21DfnInAppMessageResult")
@interface DfnInAppMessageResult : NSObject
@property (nonatomic, readonly) BOOL isSucceeded;
- (NSArray<DfnInAppMessage *> * _Nullable)getData SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nullable)getError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AdBrixRmKit9DfnResult")
@interface DfnResult : NSObject
@property (nonatomic, readonly) BOOL isSuccess;
@property (nonatomic, readonly) NSError * _Nullable error;
- (nonnull instancetype)initWithIsSuccess:(BOOL)isSuccess error:(NSError * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AdBrixRmKit7DfnUtil")
@interface DfnUtil : NSObject
+ (NSString * _Nonnull)getLanguage SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)getPushEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)getOsPushEnable SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit21GetAllCiProfileResult")
@interface GetAllCiProfileResult : CIResult
@end


SWIFT_CLASS("_TtC11AdBrixRmKit18GetCiProfileResult")
@interface GetCiProfileResult : CIResult
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit21GetSubscriptionResult")
@interface GetSubscriptionResult : CIResult
@property (nonatomic, readonly, strong) SubscriptionStatus * _Nullable value;
@end


SWIFT_CLASS("_TtC11AdBrixRmKit11KakaoButton")
@interface KakaoButton : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable urlPc;
@property (nonatomic, readonly, copy) NSString * _Nullable urlMobile;
@property (nonatomic, readonly, copy) NSString * _Nullable scheme;
@property (nonatomic, readonly, copy) NSString * _Nullable chatExtra;
@property (nonatomic, readonly, copy) NSString * _Nullable chatEvent;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AdBrixRmKit21SelfServeInAppMessage")
@interface SelfServeInAppMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull campaignId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AdBrixRmKit18SetCiProfileResult")
@interface SetCiProfileResult : CIResult
@end


SWIFT_CLASS("_TtC11AdBrixRmKit21SetSubscriptionResult")
@interface SetSubscriptionResult : CIResult
@end

enum _Type : NSInteger;
@class SubscriptionStatusBuilder;

SWIFT_CLASS("_TtC11AdBrixRmKit18SubscriptionStatus")
@interface SubscriptionStatus : NSObject
@property (nonatomic, readonly) enum _Type informativeNotificationFlag;
@property (nonatomic, readonly) enum _Type marketingNotificationFlag;
@property (nonatomic, readonly) enum _Type marketingNotificationFlagForPushChannel;
@property (nonatomic, readonly) enum _Type marketingNotificationFlagForSmsChannel;
@property (nonatomic, readonly) enum _Type marketingNotificationFlagForKakaoChannel;
@property (nonatomic, readonly) enum _Type marketingNotificationAtNightFlag;
@property (nonatomic, readonly) enum _Type marketingNotificationAtNightFlagForPushChannel;
@property (nonatomic, readonly) enum _Type marketingNotificationAtNightFlagForSmsChannel;
@property (nonatomic, readonly) enum _Type marketingNotificationAtNightFlagForKakaoChannel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (SubscriptionStatusBuilder * _Nonnull)Builder SWIFT_WARN_UNUSED_RESULT;
/// convenient function same as AdBrixRM.setSubscriptionStatus(status: AbxSubscriptionStatus, completion: (SetSubscriptionResult) -> ())
/// \code
/// // example
/// SubscriptionStatus.builder()
///     .setInformativeNotificationFlag(to: .UNSUBSCRIBED)
///     .setMarketingNotificationFlag(to: .UNSUBSCRIBED)
///     .setMarketingNotificationFlagForKakaoChannel(to: .UNSUBSCRIBED)
///     .setMarketingNotificationFlagForSmsChannel(to: .UNSUBSCRIBED)
///     .setMarketingNotificationFlagForPushChannel(to: .UNSUBSCRIBED)
///     .setMarketingNotificationAtNightFlag(to: .UNSUBSCRIBED)
///     .setMarketingNotificationAtNightFlagForSmsChannel(to: .UNSUBSCRIBED)
///     .setMarketingNotificationAtNightFlagForKakaoChannel(to: .UNSUBSCRIBED)
///     .setMarketingNotificationAtNightFlagForPushChannel(to: .UNSUBSCRIBED)
///     .build()
///     .send { result in
///         print(result)
///     }
///
/// \endcode
- (void)sendWithCompletion:(void (^ _Nonnull)(SetSubscriptionResult * _Nonnull))completion;
- (void)sendWithCompletionHandler:(void (^ _Nonnull)(SetSubscriptionResult * _Nonnull))completionHandler SWIFT_AVAILABILITY(ios,introduced=13.0);
@end

typedef SWIFT_ENUM(NSInteger, _Type, open) {
  _TypeSUBSCRIBED = 0,
  _TypeUNSUBSCRIBED = 1,
  _TypeUNDEFINED = 2,
};


SWIFT_CLASS("_TtC11AdBrixRmKit25SubscriptionStatusBuilder")
@interface SubscriptionStatusBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (SubscriptionStatusBuilder * _Nonnull)setInformativeNotificationFlagTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationFlagTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationFlagForPushChannelTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationFlagForSmsChannelTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationFlagForKakaoChannelTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationAtNightFlagTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationAtNightFlagForPushChannelTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationAtNightFlagForSmsChannelTo:(enum _Type)status;
- (SubscriptionStatusBuilder * _Nonnull)setMarketingNotificationAtNightFlagForKakaoChannelTo:(enum _Type)status;
- (SubscriptionStatus * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end





typedef SWIFT_ENUM(NSInteger, UserProfileServerError, open) {
  UserProfileServerErrorRESULT_CODE_INVALID_TOKEN = 4001,
  UserProfileServerErrorRESULT_CODE_INVALID_REQUEST = 4002,
  UserProfileServerErrorRESULT_CODE_BLOCKED_ACCOUNT = 4003,
  UserProfileServerErrorRESULT_CODE_UNAUTHORIZED = 4004,
  UserProfileServerErrorRESULT_CODE_TERMINATED_API = 4005,
  UserProfileServerErrorRESULT_CODE_RATE_LIMIT_EXCEEDED = 4006,
  UserProfileServerErrorRESULT_CODE_WRONG_PROPERTY = 4007,
  UserProfileServerErrorRESULT_CODE_INTERNAL_SERVER_ERROR = 5001,
  UserProfileServerErrorRESULT_CODE_SERVICE_MAINTENANCE = 5002,
  UserProfileServerErrorRESULT_CODE_SERVER_BUSY = 5003,
  UserProfileServerErrorRESULT_CODE_PROPERTY_REQUIRED = -253,
  UserProfileServerErrorRESULT_CODE_USER_ID_REQUIRED = -254,
  UserProfileServerErrorRESULT_CODE_UNKNOWN_ERROR = -255,
  UserProfileServerErrorRESULT_CODE_NETWORK_ERROR = -256,
  UserProfileServerErrorRESULT_CODE_NO_DATA_TO_GET = -257,
  UserProfileServerErrorRESULT_CODE_SDK_DISABLED = -258,
  UserProfileServerErrorRESULT_CODE_SDK_STATUS = -259,
};
static NSString * _Nonnull const UserProfileServerErrorDomain = @"AdBrixRmKit.UserProfileServerError";

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
